export xsmdas
UTILSDIR=../xsmutils

EXE=xsmgenspec

SOURCES= main.cpp xsmgenspec.cpp $(UTILSDIR)/xsmutils.cpp $(UTILSDIR)/xsmfilehandler.cpp $(UTILSDIR)/xsmdata.cpp $(UTILSDIR)/xsmarea.cpp  

include $(xsmdas)/makefile.common
