export xsmdas
UTILSDIR=../xsmutils

EXE=xsmaddspec

SOURCES= main.cpp xsmaddspec.cpp $(UTILSDIR)/xsmutils.cpp $(UTILSDIR)/xsmfilehandler.cpp $(UTILSDIR)/xsmdata.cpp  

include $(xsmdas)/makefile.common
