export xsmdas
UTILSDIR=../xsmutils

EXE=xsmgenlc

SOURCES= main.cpp xsmgenlc.cpp $(UTILSDIR)/xsmutils.cpp $(UTILSDIR)/xsmfilehandler.cpp $(UTILSDIR)/xsmdata.cpp $(UTILSDIR)/xsmarea.cpp 

include $(xsmdas)/makefile.common
